apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: wissemgh5/pfe_frontend:be3d7560b61d2ad59f1c2c1c72ded558d7bb1ba0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:  # Add environment variables here
            - name: BACKEND
              value: "backend:8080/api/tutorials"
          #Add other configurations as needed
          resources:
            requests:
              memory: "300Mi"  # Request 1 GiB of RAM
            limits:
              memory: "500Mi"
